travis:
  secure:
    BINSTAR_TOKEN: eetdWPpOeM8Fcuu67mWScXMw7ZROnb7SEe1nPViNcfgE3qpCFhWODqZWc+HX69PbnTbM32qYyPM27lVH0b1lkcq+8Z64QAtDcK/aJX0bICW3MDgQt9EpAMsbHCge/FMcUc3jefHELnmEUhqV/OEft+2ljbZgBSLytLRge50JUEy515V0jp1PAyPL5QjlgO4ZepAfk8iGI4An8KMMClKIM2ypqE17g6XILzAZS+Dw/grhdC4wUFl8qPJBwwU2ZVNm4TwZYqQeiGDN/deAC6ItuwiIZVK1MkhO+6rdrjDkJBzPmpmb/XhkyzNvBNcRkbsrzDAuYoQGCrSpTEcxC/xkLytJDIzYHnHilBQPvVUYDjYKlsiM5d5LGk37UZw58RlABrG7ONhxDCQCUDw5vodIYwr6m2ckh+htFZ1WjxJvNHA22vaNmzolQu4GnrwRSIy6etxLnHT579UiUG6vVf7FirtsEaLcqLXfRajQl0rIduTS/1LtcO8YTZgQb1N/7Jswi3vpg8Mh5K0J4wnIPoLbQQDW37rZ4o2JqWiyObQBqzS0oIC+z2O/TcgsMlklkwISEHU4jazW1QyrhFpY5ekjWXkzRk26C4hxQG7eJCq7abM0WJXaoKdIeLEzMhAL10xKFyApx5rYMIOBI9mQJkLPDgZDuzH9PPU5Hl0efVL8MjY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
