travis:
  secure:
    BINSTAR_TOKEN: 0p3eGQnAoDn4rNZ8dIAHm30pV9mqTXhs+wvRMKNNZ+6RXC1sHgLI3564ARuP6aeHkRYq1PqbhCespTdqNia2MLlP47rUsIigWWYfOMVCvNSxrTltwBCWnyceQxRWGBts266rADqPrKtkHHaR4Ue0jxkNBYFKlECmHCFTYmq/y1tjNtPWe00rvEexs2K+/OGh8MXVcrL8xyonEKoiq9EZGFj93rHh41ZquLjCvD/n1tSmCGf3+GMOFdqEz2Xxq+1VFZ6G4lV8ECW0DG0aqY8al0tzh3MY61c9etyzRXNHxwXXE6KULDR/PmE94BdYCtWYtyQic2DsofPWpCDS+u7xzoiS5y2DAeaKBUR4eTlr5myxUH1+0LwaWDDPTPdaRL7H6LvDgpMHRc90HCwyJabUqHiRSMo/bbG1jS7KdgdCdP19y8OQ7J9mRJSd3vlPgc/xQwSr6RMrOPEMBoWOoHLHJQKQx5MS8TcDuRrxvbsLBxWPy/5rPxFWBuSXnUqFcb4qcchE85wrCGGeHW5H1VrHiRdPVL7V8IT77saZ1dbK8iOgXpDyn74pEv3bYQNiqsPiRJMaS8iH+PRNRZ9WVDoTBT5Vh97IeRJbRc8lv2M0Jh93UOwjsFJtG3PCOQbpp7v0mYRezDC4o9MwnZoB+TjMSzILr9tf/7fL0AjEUEhV4SQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
